server:
  port: 8080
spring:
  dubbo:
    application:
      name: dubbo-c
    registry:
      address: zookeeper://192.168.16.66:2181
    protocol:
      name: dubbo
      port: 20800
    scan: com.wjl.consumer.service,com.wjl.consumer.controller