server:
  port: 8081
spring:
  dubbo:
    application:
      name: dubbo
    registry:
      address: zookeeper://192.168.16.66:2181
    protocol:
      name: dubbo
      port: 20800
    scan: com.wjl.provider.service